---
- name: install keepalived
  yum: name=keepalived
  tags:
    - keepalived:install

- name: configure keepalived
  template:
    src: etc/keepalived/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    backup: yes
  notify: restart keepalived
  tags:
    - keepalived:configure

- name: ensure keepalived is running and enabled
  service: name=keepalived state=started enabled=yes
  tags:
    - keepalived:service

# vim: set et fenc= ft=ansible sts=0 sw=2 ts=2 tw=0 :
