---
- name: docker repository
  copy: src=docker.repo dest=/etc/yum.repos.d/docker.repo

- name: install docker-engine
  yum: name=docker-engine

- name: install python-pip
  yum: name=python-pip

- name: install docker-py
  pip: name=docker-py

- name: install docker-compose
  pip: name=docker-compose

- name: install docker-custodian
  pip: name='git+https://github.com/Yelp/docker-custodian.git' editable=false

- name: enable docker service
  service: name=docker enabled=yes

- name: start docker service
  service: name=docker state=started

# vim: set et fenc=utf-8 ft=ansible sts=2 sw=2 ts=2 tw=0 :
